site_name: ACC Wiki
theme:
  name: material
  logo: assets/logo.webp
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7

        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-2
        name: Switch to light mode

repo_url: https://github.com/accsaber/wiki
repo_name: accsaber/wiki
extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/accchampcommunity
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ACC_Champ

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors
