site_name: ACC Wiki
theme:
  name: material
  favicon: assets/acc.png
  logo: assets/acc.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.instant
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7

        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-2
        name: Switch to light mode

repo_url: https://github.com/accsaber/wiki
repo_name: accsaber/wiki
extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/accchampcommunity
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ACC_Champ

extra_css:
  - assets/styles.css

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - git-revision-date-localized
